### ISSUE TITLE
ke audit return failed

### ISSUE THREAD

**Issue by luohoufu** [kubesphere/kubeeye#100]
ke audit
failed to fetch clusterRoles: the server could not find the requested resource

kubectl version --short
Client Version: v1.22.3
Server Version: v1.22.3

**Comment by ruiyaoOps** [comment]
We currently lack consideration of service robustness and compatibility with different versions, it will be added in future versions.

**Comment by ruiyaoOps** [comment]
Fixed.
https://github.com/kubesphere/kubeeye/pull/118
Get resource failure will be skipped.
