### ISSUE TITLE
The vendor directory is too large

### ISSUE THREAD

**Issue by ruiyaoOps** [kubesphere/kubeeye#134]
The vendor directory is too large, it's not necessary for most users, and affects user clone repo.
The vendor directory will be delete.

**Comment by mangoGoForward** [comment]
Users can install dependencies package by `go mod vendor`, and the vendor directory seems unnecessary.

**Comment by mangoGoForward** [comment]
I removed the vendor directory , execute `make install`, seems work good. Could we remove the vendor directory directly? @ruiyaoOps

**Comment by ruiyaoOps** [comment]
This issue needs to be discussed,We need to confirm the impact first.
