### ISSUE TITLE
kubeeye v0.3.0 running ok but main branch build and run with error

### ISSUE THREAD

**Issue by ntuwang** [kubesphere/kubeeye#187]
when i use v0.3.0, i can get audit message(but with bug when -o json), and then i try build exec file with the main branch ,when it run , it show me the error as the follow pic

1.649217524961418e+09	ERROR	controller-runtime.source	if kind is a CRD, it should be installed before calling Start	{"kind": "ClusterInsight.kubeeye.kubesphere.io", "error": "no matches for kind \"ClusterInsight\" in version \"kubeeye.kubesphere.io/v1alpha1\""}
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1
	/Users/abel/GolandProjects/kubeeye/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:137
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext
	/Users/abel/GolandProjects/kubeeye/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:233
k8s.io/apimachinery/pkg/util/wait.poll
	/Users/abel/GolandProjects/kubeeye/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:580
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext
	/Users/abel/GolandProjects/kubeeye/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:545
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1
	/Users/abel/GolandProjects/kubeeye/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:131
1.6492175356150734e+09	ERROR	controller-runtime.source	if kind is a CRD, it should be installed before calling Start	{"kind": "ClusterInsight.kubeeye.kubesphere.io", "error": "no matches for kind \"ClusterInsight\" in version \"kubeeye.kubesphere.io/v1alpha1\""}
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1
	/Users/abel/GolandProjects/kubeeye/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:137
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext
	/Users/abel/GolandProjects/kubeeye/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:233
k8s.io/apimachinery/pkg/util/wait.WaitForWithContext
	/Users/abel/GolandProjects/kubeeye/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:660
k8s.io/apimachinery/pkg/util/wait.poll
	/Users/abel/GolandProjects/kubeeye/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:594
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext
	/Users/abel/GolandProjects/kubeeye/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:545
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1
	/Users/abel/GolandProjects/kubeeye/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:131

![image](https://user-images.githubusercontent.com/11935122/161895657-c75e450c-5a5a-4c7c-a121-5881e906273c.png)

**Comment by panzhen6668** [comment]
You need to do first  create a CRD resource like this:
kubectl apply -f https://raw.githubusercontent.com/kubesphere/kubeeye/main/deploy/kubeeye.yaml
kubectl apply -f https://raw.githubusercontent.com/kubesphere/kubeeye/main/deploy/kubeeye_insights.yaml

or  use helm install 
# helm install  kubeeye deploy/chart -n kubeeye-system

**Comment by panzhen6668** [comment]
> You need to do first create a CRD resource like this:
> 
> ```
> # kubectl apply -f https://raw.githubusercontent.com/kubesphere/kubeeye/main/deploy/kubeeye.yaml
> # kubectl apply -f https://raw.githubusercontent.com/kubesphere/kubeeye/main/deploy/kubeeye_insights.yaml
> ```
> 
> or use helm install
> 
> ```
> # helm install  kubeeye deploy/chart -n kubeeye-system
> ```



> when i use v0.3.0, i can get audit message(but with bug when -o json), and then i try build exec file with the main branch ,when it run , it show me the error as the follow pic
> 
> 1.649217524961418e+09 ERROR controller-runtime.source if kind is a CRD, it should be installed before calling Start {"kind": "ClusterInsight.kubeeye.kubesphere.io", "error": "no matches for kind "ClusterInsight" in version "kubeeye.kubesphere.io/v1alpha1""} sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1 /Users/abel/GolandProjects/kubeeye/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:137 k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext /Users/abel/GolandProjects/kubeeye/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:233 k8s.io/apimachinery/pkg/util/wait.poll /Users/abel/GolandProjects/kubeeye/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:580 k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext /Users/abel/GolandProjects/kubeeye/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:545 sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1 /Users/abel/GolandProjects/kubeeye/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:131 1.6492175356150734e+09 ERROR controller-runtime.source if kind is a CRD, it should be installed before calling Start {"kind": "ClusterInsight.kubeeye.kubesphere.io", "error": "no matches for kind "ClusterInsight" in version "kubeeye.kubesphere.io/v1alpha1""} sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1 /Users/abel/GolandProjects/kubeeye/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:137 k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext /Users/abel/GolandProjects/kubeeye/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:233 k8s.io/apimachinery/pkg/util/wait.WaitForWithContext /Users/abel/GolandProjects/kubeeye/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:660 k8s.io/apimachinery/pkg/util/wait.poll /Users/abel/GolandProjects/kubeeye/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:594 k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext /Users/abel/GolandProjects/kubeeye/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:545 sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1 /Users/abel/GolandProjects/kubeeye/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:131
> 
> ![image](https://user-images.githubusercontent.com/11935122/161895657-c75e450c-5a5a-4c7c-a121-5881e906273c.png)
