### ISSUE TITLE
巡检结果可视化如何查看

### ISSUE THREAD

**Issue by wxuedong** [kubesphere/kubeeye#213]
[关于可视化查询描述](https://github.com/kubesphere/kubeeye/blob/main/README_zh.md#kubeeye-operator-%E8%83%BD%E5%81%9A%E4%BB%80%E4%B9%88)

没有找到相关的使用说明，如何操作才能看web可视化 ？ 谢谢

**Comment by ruiyaoOps** [comment]
Viewing the audit results through the website has not been released to the community, will released soon. You can pay attention to community meeting，we will notify through community meetings, thank you.

**Comment by waynezhang1984** [comment]
what's time viewing the audit results through the website
thanks a lot

**Comment by Huihuihh** [comment]
发布了吗，怎么使用
