### ISSUE TITLE
Unable to make from source

### ISSUE THREAD

**Issue by mbwmbw1337** [kubesphere/kubeeye#62]
Everytime I try to make I get a different error during the process. I tried removing the GOPROXY and that did not help.
`HypriotOS/armv7:  in ~/kubeeye
# make install
GO111MODULE=on CGO_ENABLED=0 go get -u github.com/gobuffalo/packr/v2/packr2
go: finding github.com/gobuffalo/packr/v2/packr2 latest
go: finding golang.org/x/sync latest
go: finding golang.org/x/sys latest
go: finding golang.org/x/net latest
go: finding github.com/coreos/pkg latest
go: finding github.com/kr/logfmt latest
go: github.com/coreos/bbolt@v1.3.5: parsing go.mod: unexpected module path "go.etcd.io/bbolt"
go: finding google.golang.org/genproto latest
go: finding golang.org/x/time latest
go: finding gopkg.in/check.v1 latest
go: finding golang.org/x/crypto latest
go get: error loading module requirements
make: *** [Makefile:12: install-packr2] Error 1`

**Comment by pixiake** [comment]
`GO111MODULE=on GOPROXY=https://goproxy.io CGO_ENABLED=0 go get -u github.com/gobuffalo/packr/v2/packr2`

Executing this command will report an error ?

**Comment by mbwmbw1337** [comment]
> `GO111MODULE=on GOPROXY=https://goproxy.io CGO_ENABLED=0 go get -u github.com/gobuffalo/packr/v2/packr2`
> 
> Executing this command will report an error ?

Yes.

`# GO111MODULE=on GOPROXY=https://goproxy.io CGO_ENABLED=0 go get -u github.com/gobuffalo/packr/v2/packr2
go: finding golang.org/x/sync latest
go: finding golang.org/x/sys latest
go: finding golang.org/x/xerrors latest
go: finding golang.org/x/crypto latest
go: finding golang.org/x/net latest
go: finding golang.org/x/time latest
go: finding github.com/coreos/go-systemd latest
go: finding github.com/golang/groupcache latest
go: finding gopkg.in/check.v1 latest
go: finding github.com/tmc/grpc-websocket-proxy latest
go: finding github.com/armon/consul-api latest
go: finding github.com/pkg/diff latest
go: finding go.uber.org/tools latest
go: finding github.com/xiang90/probing latest
go: finding google.golang.org/genproto latest
go: finding golang.org/x/lint latest
go: finding github.com/gopherjs/gopherjs latest
go: finding github.com/cncf/udpa/go latest
go: finding github.com/coreos/pkg latest
go: finding github.com/kr/logfmt latest
go: finding github.com/alecthomas/template latest
go: finding golang.org/x/oauth2 latest
go: finding github.com/alecthomas/units latest
go: finding github.com/modern-go/concurrent latest
go: finding github.com/dgryski/go-sip13 latest
go: finding github.com/mwitkow/go-conntrack latest
go: finding golang.org/x/exp latest
go: finding golang.org/x/term latest
go: finding gopkg.in/yaml.v3 latest
go: github.com/coreos/bbolt@v1.3.5: parsing go.mod: unexpected module path "go.etcd.io/bbolt"
go: finding golang.org/x/image latest
go get: error loading module requirements`

**Comment by mbwmbw1337** [comment]
`# GO111MODULE=on GOPROXY=https://goproxy.io CGO_ENABLED=0 go get -u github.com/gobuffalo/packr/v2/packr2
go: finding golang.org/x/sync latest
go: finding golang.org/x/sys latest
go: finding golang.org/x/xerrors latest
go: finding golang.org/x/crypto latest
go: finding golang.org/x/net latest
go: finding golang.org/x/time latest
go: finding github.com/coreos/go-systemd latest
go: finding github.com/golang/groupcache latest
go: finding gopkg.in/check.v1 latest
go: finding github.com/tmc/grpc-websocket-proxy latest
go: finding github.com/armon/consul-api latest
go: finding github.com/pkg/diff latest
go: finding go.uber.org/tools latest
go: finding github.com/xiang90/probing latest
go: finding google.golang.org/genproto latest
go: finding golang.org/x/lint latest
go: finding github.com/gopherjs/gopherjs latest
go: finding github.com/cncf/udpa/go latest
go: finding github.com/coreos/pkg latest
go: finding github.com/kr/logfmt latest
go: finding github.com/alecthomas/template latest
go: finding golang.org/x/oauth2 latest
go: finding github.com/alecthomas/units latest
go: finding github.com/modern-go/concurrent latest
go: finding github.com/dgryski/go-sip13 latest
go: finding github.com/mwitkow/go-conntrack latest
go: finding golang.org/x/exp latest
go: finding golang.org/x/term latest
go: finding gopkg.in/yaml.v3 latest
go: github.com/coreos/bbolt@v1.3.5: parsing go.mod: unexpected module path "go.etcd.io/bbolt"
go: finding golang.org/x/image latest
go get: error loading module requirements`

**Comment by pixiake** [comment]
This looks like a go module dependency issue，I think we can try the solution in the following issue:
https://github.com/etcd-io/bbolt/issues/211

**Comment by mbwmbw1337** [comment]
Thank you for your help. The issue persists. I was able to download bbolt manually by executing:
`
# go get -u go.etcd.io/bbolt
go: finding golang.org/x/sys latest
go: downloading go.etcd.io/bbolt v1.3.5
`

I then tried immediately afterwards a make install and received the same error:
`
# make install
GO111MODULE=on CGO_ENABLED=0 go get -u github.com/gobuffalo/packr/v2/packr2
go: finding github.com/gobuffalo/packr/v2/packr2 latest
go: finding golang.org/x/net latest
go: finding golang.org/x/sync latest
go: finding golang.org/x/crypto latest
go: finding github.com/tmc/grpc-websocket-proxy latest
go: finding golang.org/x/sys latest
go: finding golang.org/x/oauth2 latest
go: finding golang.org/x/xerrors latest
go: finding google.golang.org/genproto latest
go: finding github.com/golang/groupcache latest
go: finding github.com/armon/consul-api latest
go: finding golang.org/x/exp latest
**go: github.com/coreos/bbolt@v1.3.5: parsing go.mod: unexpected module path "go.etcd.io/bbolt"**
go: finding golang.org/x/lint latest
go: finding github.com/go-gl/glfw/v3.3/glfw latest
go: finding golang.org/x/time latest
go get: error loading module requirements
make: *** [Makefile:12: install-packr2] Error 1
`

**Comment by JohnNiang** [comment]
Same error for me.

```bash
➜  kubeeye git:(main) make install
GO111MODULE=on GOPROXY=https://goproxy.io CGO_ENABLED=0 go get -u github.com/gobuffalo/packr/v2/packr2
go: downloading github.com/gobuffalo/packr/v2 v2.8.1
go: downloading github.com/gobuffalo/packr v1.30.1
go: downloading github.com/gobuffalo/logger v1.0.3
go: downloading github.com/spf13/cobra v1.1.3
go: downloading github.com/sirupsen/logrus v1.8.0
go: downloading golang.org/x/tools v0.1.0
go: downloading github.com/gobuffalo/packd v1.0.0
go: downloading github.com/markbates/oncer v1.0.0
go: downloading github.com/markbates/safe v1.0.1
go: downloading github.com/karrick/godirwalk v1.16.1
go: downloading github.com/markbates/errx v1.1.0
go: downloading github.com/rogpeppe/go-internal v1.7.0
go: downloading golang.org/x/sync v0.0.0-20210220032951-036812b2e83c
go: downloading github.com/gobuffalo/logger v1.0.4
go: downloading github.com/sirupsen/logrus v1.8.1
go: downloading golang.org/x/sys v0.0.0-20210305230114-8fe3ee5dd75b
go: downloading github.com/magefile/mage v1.11.0
go: downloading golang.org/x/crypto v0.0.0-20210513164829-c07d793c2f9a
go: downloading github.com/rogpeppe/go-internal v1.8.0
go: downloading golang.org/x/tools v0.1.2
go: downloading golang.org/x/term v0.0.0-20210220032956-6a3ed077a48d
go: downloading golang.org/x/sys v0.0.0-20210531080801-fdfd190a6549
go: downloading golang.org/x/term v0.0.0-20210503060354-a79de5458b56
go get: upgraded github.com/gobuffalo/logger v1.0.3 => v1.0.4
go get: upgraded github.com/rogpeppe/go-internal v1.7.0 => v1.8.0
go get: upgraded github.com/sirupsen/logrus v1.8.0 => v1.8.1
go get: upgraded golang.org/x/crypto v0.0.0-20210220033148-5ea612d1eb83 => v0.0.0-20210513164829-c07d793c2f9a
go get: upgraded golang.org/x/net v0.0.0-20201021035429-f5854403a974 => v0.0.0-20210405180319-a5a99cb37ef4
go get: upgraded golang.org/x/sys v0.0.0-20210305230114-8fe3ee5dd75b => v0.0.0-20210531080801-fdfd190a6549
go get: upgraded golang.org/x/term v0.0.0-20210220032956-6a3ed077a48d => v0.0.0-20210503060354-a79de5458b56
go get: upgraded golang.org/x/tools v0.1.0 => v0.1.2
/home/johnniang/go/bin/packr2 build -a -o "ke" *.go
go: downloading github.com/pkg/errors v0.8.1
go: downloading sigs.k8s.io/controller-runtime v0.6.3
go: downloading github.com/qri-io/jsonschema v0.1.1
go: downloading github.com/qri-io/jsonpointer v0.1.0
../../../go/pkg/mod/golang.org/x/oauth2@v0.0.0-20190604053449-0f29369cfe45/google/default.go:17:2: missing go.sum entry for module providing package cloud.google.com/go/compute/metadata; to add:
	go mod download cloud.google.com/go
../../../go/pkg/mod/k8s.io/client-go@v0.18.6/plugin/pkg/client/auth/azure/azure.go:28:2: missing go.sum entry for module providing package github.com/Azure/go-autorest/autorest; to add:
	go mod download github.com/Azure/go-autorest/autorest
../../../go/pkg/mod/k8s.io/client-go@v0.18.6/plugin/pkg/client/auth/azure/azure.go:29:2: missing go.sum entry for module providing package github.com/Azure/go-autorest/autorest/adal; to add:
	go mod download github.com/Azure/go-autorest/autorest github.com/Azure/go-autorest/autorest/adal
../../../go/pkg/mod/k8s.io/client-go@v0.18.6/plugin/pkg/client/auth/azure/azure.go:30:2: missing go.sum entry for module providing package github.com/Azure/go-autorest/autorest/azure; to add:
	go mod download github.com/Azure/go-autorest/autorest
../../../go/pkg/mod/k8s.io/client-go@v0.18.6/plugin/pkg/client/auth/openstack/openstack.go:25:2: missing go.sum entry for module providing package github.com/gophercloud/gophercloud; to add:
	go mod download github.com/gophercloud/gophercloud
../../../go/pkg/mod/k8s.io/client-go@v0.18.6/plugin/pkg/client/auth/openstack/openstack.go:26:2: missing go.sum entry for module providing package github.com/gophercloud/gophercloud/openstack; to add:
	go mod download github.com/gophercloud/gophercloud
../../../go/pkg/mod/golang.org/x/oauth2@v0.0.0-20190604053449-0f29369cfe45/internal/token.go:23:2: missing go.sum entry for module providing package golang.org/x/net/context/ctxhttp; to add:
	go mod download golang.org/x/net
../../../go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/net/http.go:34:2: missing go.sum entry for module providing package golang.org/x/net/http2; to add:
	go mod download golang.org/x/net
pkg/validator/validator-packr.go:8:8: package home/johnniang/workspace/kubesphere/kubeeye/packrd is not in GOROOT (/usr/lib/go/src/home/johnniang/workspace/kubesphere/kubeeye/packrd)
Error: exit status 1
Usage:
  packr2 build [flags]

Flags:
  -h, --help   help for build

Global Flags:
      --ignore-imports     when set to true packr won't resolve imports for boxes
      --legacy             uses the legacy resolution and packing system (assumes first arg || pwd for input path)
      --silent             silences all output
      --store-cmd string   sub command to use for packing
  -v, --verbose            enables verbose logging

make: *** [Makefile:13: install-packr2] Error 1
```
