### ISSUE TITLE
Make it work with `go install` and `brew install`

### ISSUE THREAD

**Issue by KIVagant** [kubesphere/kubeeye#66]
Hi. The tool looks interesting but in order to make the installation simpler, would be nice to support these two options:

1. `go install` (and `go get`) is failing now
```
$ go install github.com/kubesphere/kubeeye
go: finding module for package github.com/kubesphere/kubeeye
go: found github.com/kubesphere/kubeeye in github.com/kubesphere/kubeeye v0.1.0
go: github.com/kubesphere/kubeeye: github.com/kubesphere/kubeeye@v0.1.0: parsing go.mod:
	module declares its path as: kubeye
	        but was required as: github.com/kubesphere/kubeeye
```

2. `brew install` is missing

**Comment by FeynmanZhou** [comment]
Great proposals! The second one is supposed to be added to the roadmap. @ruiyaoOps Could you pls help to take at the installation issue?

**Comment by ruiyaoOps** [comment]
@FeynmanZhou It can work with go install
you can do it by following these types:
git clone https://github.com/kubesphere/kubeeye.git
cd kubeeye
GOOS=linux go build
rename kubeeye ke kubeeye
chmod +x ke
mv ke /usr/local/bin/

**Comment by ruiyaoOps** [comment]
> Hi. The tool looks interesting but in order to make the installation simpler, would be nice to support these two options:
> 
> 1. `go install` (and `go get`) is failing now
> 
> ```
> $ go install github.com/kubesphere/kubeeye
> go: finding module for package github.com/kubesphere/kubeeye
> go: found github.com/kubesphere/kubeeye in github.com/kubesphere/kubeeye v0.1.0
> go: github.com/kubesphere/kubeeye: github.com/kubesphere/kubeeye@v0.1.0: parsing go.mod:
> 	module declares its path as: kubeye
> 	        but was required as: github.com/kubesphere/kubeeye
> ```
> 
> 1. `brew install` is missing

It looks like missing module in go.mod, it will have a try.

**Comment by ruiyaoOps** [comment]
@KIVagant I had made a test, kubeeye is ok, maybe wrong with your golang environment.

**Comment by ruiyaoOps** [comment]
I don't think we need any installation here, but need to provide binaries that can use in different environments. @FeynmanZhou

**Comment by FeynmanZhou** [comment]
Agree, binary is necessary.

**Comment by ruiyaoOps** [comment]
I have added binary files to tags v0.2.0,you can download the binary file. @KIVagant @FeynmanZhou

**Comment by ruiyaoOps** [comment]
https://github.com/kubesphere/kubeeye/releases/download/v0.2.0/kubeeye-0.2.0-mac-amd64.zip
This binary worked on macOS
