### ISSUE TITLE
panic: stat /checks/hostIPCSet.yaml: no such file or directory

### ISSUE THREAD

**Issue by llhl001** [kubesphere/kubeeye#69]
kubeeye -h
panic: stat /checks/hostIPCSet.yaml: no such file or directory

goroutine 1 [running]:
kubeeye/pkg/validator.init.0()
	/opt/kubeeye/pkg/validator/schema.go:65 +0x2d6

**Comment by nanohest** [comment]
getting this too
OS: MacOS
Kubeeye version: 0.2.0

**Comment by patsevanton** [comment]
Same issue if download binary file and run kubeeye

**Comment by ruiyaoOps** [comment]
@patsevanton  please `git clone https://github.com/kubesphere/kubeeye.git` and `make install`.
The binary file execution on some environments will report the error, the cause of the problem has not been found.

**Comment by patsevanton** [comment]
@ruiyaoOps Thanks for answer.
I add kubeeye to binenv https://github.com/devops-works/binenv/pull/124
install kubeeye
```
binenv install kubeeye
```
And i wait fix this error

**Comment by ruiyaoOps** [comment]
@patsevanton 
Please confirm whether you have installed the Golang environment first. 
Kubeeye runs on Golang。

**Comment by patsevanton** [comment]
@ruiyaoOps Other golang project compile to binary and dont requirenment Golang environment.
Are project have plan run kubeeye without Golang environment?

**Comment by ruiyaoOps** [comment]
I think there are some problems with the binary package, not sure, I will try later.

**Comment by ruiyaoOps** [comment]
I think there are some problems with the binary package, not sure, I will try later.
