### ISSUE TITLE
documentation: NodeCPU

### ISSUE THREAD

**Issue by theonlydoo** [kubesphere/kubeeye#70]
Hey,

I saw that `NodeCPU` could be a check item but i dont see it implemented nor documented, am i missing something?

**Comment by pixiake** [comment]
kubeeye analyzes the events of the nodes in the cluster to get the health status of the nodes, such as insufficient cpu, insufficient memory, insufficient disk.

**Comment by theonlydoo** [comment]
Yes, my question was more about: is this being done by NPD? How does kubeeye notifies about a cpu starvation?

**Comment by pixiake** [comment]
`insufficient cpu, insufficient memory, insufficient disk` were checked by kubelet, then this information was written to the events of the node.

**Comment by theonlydoo** [comment]
would  it be possible to have some documentation about this specific use case? maybe others? it's kind of cryptic for a new user to guess what to do in this case.
