### ISSUE TITLE
A bug occurs when my custom resource  ownerReferences has a circular dependency

### ISSUE THREAD

**Issue by shaot001** [kubesphere/kubeeye#74]
Two CRD are like this
Kind A OwnerReferences Kind B
Kind B OwnerReferences Kind A
When the program runs to get the resource Kind A or KindB ，it will be stuck in an infinite loop

The code that causes this problem is in
/kubeeye/pkg/kube/workload.go            73 lines

Although this scenario is not very common，Or maybe it just shouldn't exist，But that's what my company does，Does it need to be improved

**Comment by yuswift** [comment]
IMO, this case should not exist.

**Comment by shaot001** [comment]
Thank you for your reply. In order to use it, I have modified the source code and ignored our company's own recycling dependent resources
